spring:
  data:
    mongodb:
      database: bookstock2

  datasource:
     url: jdbc:postgresql://192.168.1.56:5432/bookstock2
     username: user1
     password: jw8s0F4
     initialization-mode: always
     schema: schema.sql
     #data: data.sql
     data:

  batch:
    initialize-schema: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
